// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package post

import (
	"context"
	"sync"
)

// Ensure, that PDSRecordAPIMock does implement PDSRecordAPI.
// If this is not the case, regenerate this file with moq.
var _ PDSRecordAPI = &PDSRecordAPIMock{}

// PDSRecordAPIMock is a mock implementation of PDSRecordAPI.
//
//	func TestSomethingThatUsesPDSRecordAPI(t *testing.T) {
//
//		// make and configure a mocked PDSRecordAPI
//		mockedPDSRecordAPI := &PDSRecordAPIMock{
//			DeleteRecordFunc: func(ctx context.Context, accountDID string, sessionID string, collection string, rkey string) error {
//				panic("mock out the DeleteRecord method")
//			},
//			PutRecordFunc: func(ctx context.Context, accountDID string, sessionID string, collection string, rkey string, record map[string]any) (string, error) {
//				panic("mock out the PutRecord method")
//			},
//		}
//
//		// use mockedPDSRecordAPI in code that requires PDSRecordAPI
//		// and then make assertions.
//
//	}
type PDSRecordAPIMock struct {
	// DeleteRecordFunc mocks the DeleteRecord method.
	DeleteRecordFunc func(ctx context.Context, accountDID string, sessionID string, collection string, rkey string) error

	// PutRecordFunc mocks the PutRecord method.
	PutRecordFunc func(ctx context.Context, accountDID string, sessionID string, collection string, rkey string, record map[string]any) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// DeleteRecord holds details about calls to the DeleteRecord method.
		DeleteRecord []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AccountDID is the accountDID argument value.
			AccountDID string
			// SessionID is the sessionID argument value.
			SessionID string
			// Collection is the collection argument value.
			Collection string
			// Rkey is the rkey argument value.
			Rkey string
		}
		// PutRecord holds details about calls to the PutRecord method.
		PutRecord []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AccountDID is the accountDID argument value.
			AccountDID string
			// SessionID is the sessionID argument value.
			SessionID string
			// Collection is the collection argument value.
			Collection string
			// Rkey is the rkey argument value.
			Rkey string
			// Record is the record argument value.
			Record map[string]any
		}
	}
	lockDeleteRecord sync.RWMutex
	lockPutRecord    sync.RWMutex
}

// DeleteRecord calls DeleteRecordFunc.
func (mock *PDSRecordAPIMock) DeleteRecord(ctx context.Context, accountDID string, sessionID string, collection string, rkey string) error {
	if mock.DeleteRecordFunc == nil {
		panic("PDSRecordAPIMock.DeleteRecordFunc: method is nil but PDSRecordAPI.DeleteRecord was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		AccountDID string
		SessionID  string
		Collection string
		Rkey       string
	}{
		Ctx:        ctx,
		AccountDID: accountDID,
		SessionID:  sessionID,
		Collection: collection,
		Rkey:       rkey,
	}
	mock.lockDeleteRecord.Lock()
	mock.calls.DeleteRecord = append(mock.calls.DeleteRecord, callInfo)
	mock.lockDeleteRecord.Unlock()
	return mock.DeleteRecordFunc(ctx, accountDID, sessionID, collection, rkey)
}

// DeleteRecordCalls gets all the calls that were made to DeleteRecord.
// Check the length with:
//
//	len(mockedPDSRecordAPI.DeleteRecordCalls())
func (mock *PDSRecordAPIMock) DeleteRecordCalls() []struct {
	Ctx        context.Context
	AccountDID string
	SessionID  string
	Collection string
	Rkey       string
} {
	var calls []struct {
		Ctx        context.Context
		AccountDID string
		SessionID  string
		Collection string
		Rkey       string
	}
	mock.lockDeleteRecord.RLock()
	calls = mock.calls.DeleteRecord
	mock.lockDeleteRecord.RUnlock()
	return calls
}

// PutRecord calls PutRecordFunc.
func (mock *PDSRecordAPIMock) PutRecord(ctx context.Context, accountDID string, sessionID string, collection string, rkey string, record map[string]any) (string, error) {
	if mock.PutRecordFunc == nil {
		panic("PDSRecordAPIMock.PutRecordFunc: method is nil but PDSRecordAPI.PutRecord was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		AccountDID string
		SessionID  string
		Collection string
		Rkey       string
		Record     map[string]any
	}{
		Ctx:        ctx,
		AccountDID: accountDID,
		SessionID:  sessionID,
		Collection: collection,
		Rkey:       rkey,
		Record:     record,
	}
	mock.lockPutRecord.Lock()
	mock.calls.PutRecord = append(mock.calls.PutRecord, callInfo)
	mock.lockPutRecord.Unlock()
	return mock.PutRecordFunc(ctx, accountDID, sessionID, collection, rkey, record)
}

// PutRecordCalls gets all the calls that were made to PutRecord.
// Check the length with:
//
//	len(mockedPDSRecordAPI.PutRecordCalls())
func (mock *PDSRecordAPIMock) PutRecordCalls() []struct {
	Ctx        context.Context
	AccountDID string
	SessionID  string
	Collection string
	Rkey       string
	Record     map[string]any
} {
	var calls []struct {
		Ctx        context.Context
		AccountDID string
		SessionID  string
		Collection string
		Rkey       string
		Record     map[string]any
	}
	mock.lockPutRecord.RLock()
	calls = mock.calls.PutRecord
	mock.lockPutRecord.RUnlock()
	return calls
}
