// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package post

import (
	"arktie.org/ent"
	"context"
	"github.com/google/uuid"
	"sync"
)

// Ensure, that PostResourceMock does implement PostResource.
// If this is not the case, regenerate this file with moq.
var _ PostResource = &PostResourceMock{}

// PostResourceMock is a mock implementation of PostResource.
//
//	func TestSomethingThatUsesPostResource(t *testing.T) {
//
//		// make and configure a mocked PostResource
//		mockedPostResource := &PostResourceMock{
//			CreateFunc: func(ctx context.Context, userID uuid.UUID, markdownContent *string) (*ent.Post, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, id uuid.UUID) (*ent.Post, error) {
//				panic("mock out the Get method")
//			},
//			UpdateFunc: func(ctx context.Context, id uuid.UUID, userID uuid.UUID, markdownContent *string) (*ent.Post, error) {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedPostResource in code that requires PostResource
//		// and then make assertions.
//
//	}
type PostResourceMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, userID uuid.UUID, markdownContent *string) (*ent.Post, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id uuid.UUID) (*ent.Post, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, id uuid.UUID, userID uuid.UUID, markdownContent *string) (*ent.Post, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// MarkdownContent is the markdownContent argument value.
			MarkdownContent *string
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// UserID is the userID argument value.
			UserID uuid.UUID
			// MarkdownContent is the markdownContent argument value.
			MarkdownContent *string
		}
	}
	lockCreate sync.RWMutex
	lockDelete sync.RWMutex
	lockGet    sync.RWMutex
	lockUpdate sync.RWMutex
}

// Create calls CreateFunc.
func (mock *PostResourceMock) Create(ctx context.Context, userID uuid.UUID, markdownContent *string) (*ent.Post, error) {
	if mock.CreateFunc == nil {
		panic("PostResourceMock.CreateFunc: method is nil but PostResource.Create was just called")
	}
	callInfo := struct {
		Ctx             context.Context
		UserID          uuid.UUID
		MarkdownContent *string
	}{
		Ctx:             ctx,
		UserID:          userID,
		MarkdownContent: markdownContent,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, userID, markdownContent)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedPostResource.CreateCalls())
func (mock *PostResourceMock) CreateCalls() []struct {
	Ctx             context.Context
	UserID          uuid.UUID
	MarkdownContent *string
} {
	var calls []struct {
		Ctx             context.Context
		UserID          uuid.UUID
		MarkdownContent *string
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *PostResourceMock) Delete(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	if mock.DeleteFunc == nil {
		panic("PostResourceMock.DeleteFunc: method is nil but PostResource.Delete was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ID     uuid.UUID
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		ID:     id,
		UserID: userID,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id, userID)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedPostResource.DeleteCalls())
func (mock *PostResourceMock) DeleteCalls() []struct {
	Ctx    context.Context
	ID     uuid.UUID
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		ID     uuid.UUID
		UserID uuid.UUID
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *PostResourceMock) Get(ctx context.Context, id uuid.UUID) (*ent.Post, error) {
	if mock.GetFunc == nil {
		panic("PostResourceMock.GetFunc: method is nil but PostResource.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedPostResource.GetCalls())
func (mock *PostResourceMock) GetCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *PostResourceMock) Update(ctx context.Context, id uuid.UUID, userID uuid.UUID, markdownContent *string) (*ent.Post, error) {
	if mock.UpdateFunc == nil {
		panic("PostResourceMock.UpdateFunc: method is nil but PostResource.Update was just called")
	}
	callInfo := struct {
		Ctx             context.Context
		ID              uuid.UUID
		UserID          uuid.UUID
		MarkdownContent *string
	}{
		Ctx:             ctx,
		ID:              id,
		UserID:          userID,
		MarkdownContent: markdownContent,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, id, userID, markdownContent)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedPostResource.UpdateCalls())
func (mock *PostResourceMock) UpdateCalls() []struct {
	Ctx             context.Context
	ID              uuid.UUID
	UserID          uuid.UUID
	MarkdownContent *string
} {
	var calls []struct {
		Ctx             context.Context
		ID              uuid.UUID
		UserID          uuid.UUID
		MarkdownContent *string
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
