// Code generated by ent, DO NOT EDIT.

package post

import (
	"time"

	"arktie.org/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldUserID, v))
}

// MarkdownContent applies equality check predicate on the "markdown_content" field. It's identical to MarkdownContentEQ.
func MarkdownContent(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldMarkdownContent, v))
}

// AtURL applies equality check predicate on the "at_url" field. It's identical to AtURLEQ.
func AtURL(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldAtURL, v))
}

// PublishFrom applies equality check predicate on the "publish_from" field. It's identical to PublishFromEQ.
func PublishFrom(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldPublishFrom, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldUserID, vs...))
}

// MarkdownContentEQ applies the EQ predicate on the "markdown_content" field.
func MarkdownContentEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldMarkdownContent, v))
}

// MarkdownContentNEQ applies the NEQ predicate on the "markdown_content" field.
func MarkdownContentNEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldMarkdownContent, v))
}

// MarkdownContentIn applies the In predicate on the "markdown_content" field.
func MarkdownContentIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldMarkdownContent, vs...))
}

// MarkdownContentNotIn applies the NotIn predicate on the "markdown_content" field.
func MarkdownContentNotIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldMarkdownContent, vs...))
}

// MarkdownContentGT applies the GT predicate on the "markdown_content" field.
func MarkdownContentGT(v string) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldMarkdownContent, v))
}

// MarkdownContentGTE applies the GTE predicate on the "markdown_content" field.
func MarkdownContentGTE(v string) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldMarkdownContent, v))
}

// MarkdownContentLT applies the LT predicate on the "markdown_content" field.
func MarkdownContentLT(v string) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldMarkdownContent, v))
}

// MarkdownContentLTE applies the LTE predicate on the "markdown_content" field.
func MarkdownContentLTE(v string) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldMarkdownContent, v))
}

// MarkdownContentContains applies the Contains predicate on the "markdown_content" field.
func MarkdownContentContains(v string) predicate.Post {
	return predicate.Post(sql.FieldContains(FieldMarkdownContent, v))
}

// MarkdownContentHasPrefix applies the HasPrefix predicate on the "markdown_content" field.
func MarkdownContentHasPrefix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasPrefix(FieldMarkdownContent, v))
}

// MarkdownContentHasSuffix applies the HasSuffix predicate on the "markdown_content" field.
func MarkdownContentHasSuffix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasSuffix(FieldMarkdownContent, v))
}

// MarkdownContentIsNil applies the IsNil predicate on the "markdown_content" field.
func MarkdownContentIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldMarkdownContent))
}

// MarkdownContentNotNil applies the NotNil predicate on the "markdown_content" field.
func MarkdownContentNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldMarkdownContent))
}

// MarkdownContentEqualFold applies the EqualFold predicate on the "markdown_content" field.
func MarkdownContentEqualFold(v string) predicate.Post {
	return predicate.Post(sql.FieldEqualFold(FieldMarkdownContent, v))
}

// MarkdownContentContainsFold applies the ContainsFold predicate on the "markdown_content" field.
func MarkdownContentContainsFold(v string) predicate.Post {
	return predicate.Post(sql.FieldContainsFold(FieldMarkdownContent, v))
}

// AtURLEQ applies the EQ predicate on the "at_url" field.
func AtURLEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldAtURL, v))
}

// AtURLNEQ applies the NEQ predicate on the "at_url" field.
func AtURLNEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldAtURL, v))
}

// AtURLIn applies the In predicate on the "at_url" field.
func AtURLIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldAtURL, vs...))
}

// AtURLNotIn applies the NotIn predicate on the "at_url" field.
func AtURLNotIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldAtURL, vs...))
}

// AtURLGT applies the GT predicate on the "at_url" field.
func AtURLGT(v string) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldAtURL, v))
}

// AtURLGTE applies the GTE predicate on the "at_url" field.
func AtURLGTE(v string) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldAtURL, v))
}

// AtURLLT applies the LT predicate on the "at_url" field.
func AtURLLT(v string) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldAtURL, v))
}

// AtURLLTE applies the LTE predicate on the "at_url" field.
func AtURLLTE(v string) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldAtURL, v))
}

// AtURLContains applies the Contains predicate on the "at_url" field.
func AtURLContains(v string) predicate.Post {
	return predicate.Post(sql.FieldContains(FieldAtURL, v))
}

// AtURLHasPrefix applies the HasPrefix predicate on the "at_url" field.
func AtURLHasPrefix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasPrefix(FieldAtURL, v))
}

// AtURLHasSuffix applies the HasSuffix predicate on the "at_url" field.
func AtURLHasSuffix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasSuffix(FieldAtURL, v))
}

// AtURLIsNil applies the IsNil predicate on the "at_url" field.
func AtURLIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldAtURL))
}

// AtURLNotNil applies the NotNil predicate on the "at_url" field.
func AtURLNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldAtURL))
}

// AtURLEqualFold applies the EqualFold predicate on the "at_url" field.
func AtURLEqualFold(v string) predicate.Post {
	return predicate.Post(sql.FieldEqualFold(FieldAtURL, v))
}

// AtURLContainsFold applies the ContainsFold predicate on the "at_url" field.
func AtURLContainsFold(v string) predicate.Post {
	return predicate.Post(sql.FieldContainsFold(FieldAtURL, v))
}

// PublishFromEQ applies the EQ predicate on the "publish_from" field.
func PublishFromEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldPublishFrom, v))
}

// PublishFromNEQ applies the NEQ predicate on the "publish_from" field.
func PublishFromNEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldPublishFrom, v))
}

// PublishFromIn applies the In predicate on the "publish_from" field.
func PublishFromIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldPublishFrom, vs...))
}

// PublishFromNotIn applies the NotIn predicate on the "publish_from" field.
func PublishFromNotIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldPublishFrom, vs...))
}

// PublishFromGT applies the GT predicate on the "publish_from" field.
func PublishFromGT(v string) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldPublishFrom, v))
}

// PublishFromGTE applies the GTE predicate on the "publish_from" field.
func PublishFromGTE(v string) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldPublishFrom, v))
}

// PublishFromLT applies the LT predicate on the "publish_from" field.
func PublishFromLT(v string) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldPublishFrom, v))
}

// PublishFromLTE applies the LTE predicate on the "publish_from" field.
func PublishFromLTE(v string) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldPublishFrom, v))
}

// PublishFromContains applies the Contains predicate on the "publish_from" field.
func PublishFromContains(v string) predicate.Post {
	return predicate.Post(sql.FieldContains(FieldPublishFrom, v))
}

// PublishFromHasPrefix applies the HasPrefix predicate on the "publish_from" field.
func PublishFromHasPrefix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasPrefix(FieldPublishFrom, v))
}

// PublishFromHasSuffix applies the HasSuffix predicate on the "publish_from" field.
func PublishFromHasSuffix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasSuffix(FieldPublishFrom, v))
}

// PublishFromIsNil applies the IsNil predicate on the "publish_from" field.
func PublishFromIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldPublishFrom))
}

// PublishFromNotNil applies the NotNil predicate on the "publish_from" field.
func PublishFromNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldPublishFrom))
}

// PublishFromEqualFold applies the EqualFold predicate on the "publish_from" field.
func PublishFromEqualFold(v string) predicate.Post {
	return predicate.Post(sql.FieldEqualFold(FieldPublishFrom, v))
}

// PublishFromContainsFold applies the ContainsFold predicate on the "publish_from" field.
func PublishFromContainsFold(v string) predicate.Post {
	return predicate.Post(sql.FieldContainsFold(FieldPublishFrom, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Post) predicate.Post {
	return predicate.Post(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Post) predicate.Post {
	return predicate.Post(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Post) predicate.Post {
	return predicate.Post(sql.NotPredicates(p))
}
