// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"arktie.org/internal/data"
	"arktie.org/internal/data/client"
	"arktie.org/internal/server"
	"arktie.org/internal/service/post"
	"github.com/mazrean/kessoku"
)

func newApp(config *data.Config) (*App, error) {
	firehoseLogHandler := kessoku.Provide(func() *FirehoseLogHandler {
		return &FirehoseLogHandler{}
	}).Fn()()
	var err error
	event, err := kessoku.Provide(client.NewEvent).Fn()(config)
	if err != nil {
		var zero *App
		return zero, err
	}
	firehosePostHandler := kessoku.Bind[server.FirehosePostHandler](kessoku.Provide(func(h *FirehoseLogHandler) server.FirehosePostHandler {
		return h
	})).Fn()(firehoseLogHandler)
	firehoseService := kessoku.Provide(post.NewFirehoseService).Fn()(config, event)
	firehoseListener := kessoku.Provide(server.NewFirehoseListener).Fn()(event, firehosePostHandler)
	app := kessoku.Provide(func(cfg *data.Config, event *client.Event, firehose *post.FirehoseService, _ *server.FirehoseListener) *App {
		return &App{Config: cfg, Event: event, Firehose: firehose}
	}).Fn()(config, event, firehoseService, firehoseListener)
	return app, nil
}
