// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"arktie.org/internal/data"
	"arktie.org/internal/data/client"
	"arktie.org/internal/server"
	"arktie.org/internal/service/oauth"
	"arktie.org/internal/service/post"
	post0 "arktie.org/internal/usecase/post"
	"arktie.org/internal/usecase/user"
	"github.com/mazrean/kessoku"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"
	"net/http"
)

func newApp(config *data.Config) (*App, error) {
	var err error
	event, err := kessoku.Provide(client.NewEvent).Fn()(config)
	if err != nil {
		var zero *App
		return zero, err
	}
	var err0 error
	database, err0 := kessoku.Provide(client.NewDatabase).Fn()(config)
	if err0 != nil {
		var zero *App
		return zero, err0
	}
	var err1 error
	oauth0, err1 := kessoku.Provide(client.NewOAuth).Fn()(config, database)
	if err1 != nil {
		var zero *App
		return zero, err1
	}
	usecase := kessoku.Provide(post0.NewUsecase).Fn()(database)
	usecase0 := kessoku.Provide(user.NewUsecase).Fn()(database)
	pdsrecord := kessoku.Provide(post0.NewPDSRecord).Fn()(config, oauth0)
	postResource := kessoku.Bind[post.PostResource](kessoku.Provide(func(uc *post0.Usecase) post.PostResource {
		return uc
	})).Fn()(usecase)
	userAttempter := kessoku.Bind[oauth.UserAttempter](kessoku.Provide(func(uc *user.Usecase) oauth.UserAttempter {
		return uc
	})).Fn()(usecase0)
	pdsrecordAPI := kessoku.Bind[post.PDSRecordAPI](kessoku.Provide(func(p *post0.PDSRecord) post.PDSRecordAPI {
		return p
	})).Fn()(pdsrecord)
	resourceService := kessoku.Provide(post.NewResourceService).Fn()(event, postResource)
	service := kessoku.Provide(oauth.NewService).Fn()(config, oauth0, userAttempter)
	syncService := kessoku.Provide(post.NewSyncService).Fn()(database, pdsrecordAPI)
	oauthHandler := kessoku.Bind[server.OAuthHandler](kessoku.Provide(func(s *oauth.Service) server.OAuthHandler {
		return s
	})).Fn()(service)
	postPusher := kessoku.Bind[server.PostPusher](kessoku.Provide(func(s *post.SyncService) server.PostPusher {
		return s
	})).Fn()(syncService)
	handler := kessoku.Provide(server.NewHandler).Fn()(config, database, oauthHandler, resourceService)
	appListener := kessoku.Provide(server.NewAppListener).Fn()(event, postPusher)
	app := kessoku.Provide(func(cfg *data.Config, event *client.Event, handler http.Handler, _ *server.AppListener) *App {
		return &App{HTTP: &http.Server{Addr: cfg.Server.Addr, Handler: h2c.NewHandler(handler, &http2.Server{})}, Router: event.Router}
	}).Fn()(config, event, handler, appListener)
	return app, nil
}
