// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"arktie.org/internal/data"
	"arktie.org/internal/server"
	"arktie.org/internal/service/oauth"
	"arktie.org/internal/usecase/user"
	"github.com/mazrean/kessoku"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"
	"net/http"
)

func newServer(config *data.Config) (*http.Server, error) {
	var err error
	client, err := kessoku.Provide(data.NewClient).Fn()(config)
	if err != nil {
		var zero *http.Server
		return zero, err
	}
	usecase := kessoku.Provide(user.NewUsecase).Fn()(client)
	userAttempter := kessoku.Bind[oauth.UserAttempter](kessoku.Provide(func(uc *user.Usecase) oauth.UserAttempter {
		return uc
	})).Fn()(usecase)
	service := kessoku.Provide(oauth.NewService).Fn()(config, client, userAttempter)
	oauthHandler := kessoku.Bind[server.OAuthHandler](kessoku.Provide(func(s *oauth.Service) server.OAuthHandler {
		return s
	})).Fn()(service)
	handler := kessoku.Provide(server.NewHandler).Fn()(config, oauthHandler)
	server0 := kessoku.Provide(func(cfg *data.Config, handler http.Handler) *http.Server {
		return &http.Server{Addr: cfg.Server.Addr, Handler: h2c.NewHandler(handler, &http2.Server{})}
	}).Fn()(config, handler)
	return server0, nil
}
