// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"arktie.org/ent/post"
	"arktie.org/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PostUpdate is the builder for updating Post entities.
type PostUpdate struct {
	config
	hooks    []Hook
	mutation *PostMutation
}

// Where appends a list predicates to the PostUpdate builder.
func (_u *PostUpdate) Where(ps ...predicate.Post) *PostUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PostUpdate) SetUserID(v uuid.UUID) *PostUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PostUpdate) SetNillableUserID(v *uuid.UUID) *PostUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetMarkdownContent sets the "markdown_content" field.
func (_u *PostUpdate) SetMarkdownContent(v string) *PostUpdate {
	_u.mutation.SetMarkdownContent(v)
	return _u
}

// SetNillableMarkdownContent sets the "markdown_content" field if the given value is not nil.
func (_u *PostUpdate) SetNillableMarkdownContent(v *string) *PostUpdate {
	if v != nil {
		_u.SetMarkdownContent(*v)
	}
	return _u
}

// SetAtURL sets the "at_url" field.
func (_u *PostUpdate) SetAtURL(v string) *PostUpdate {
	_u.mutation.SetAtURL(v)
	return _u
}

// SetNillableAtURL sets the "at_url" field if the given value is not nil.
func (_u *PostUpdate) SetNillableAtURL(v *string) *PostUpdate {
	if v != nil {
		_u.SetAtURL(*v)
	}
	return _u
}

// ClearAtURL clears the value of the "at_url" field.
func (_u *PostUpdate) ClearAtURL() *PostUpdate {
	_u.mutation.ClearAtURL()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PostUpdate) SetUpdatedAt(v time.Time) *PostUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PostMutation object of the builder.
func (_u *PostUpdate) Mutation() *PostMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PostUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PostUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PostUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := post.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *PostUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(post.Table, post.Columns, sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(post.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.MarkdownContent(); ok {
		_spec.SetField(post.FieldMarkdownContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.AtURL(); ok {
		_spec.SetField(post.FieldAtURL, field.TypeString, value)
	}
	if _u.mutation.AtURLCleared() {
		_spec.ClearField(post.FieldAtURL, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{post.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PostUpdateOne is the builder for updating a single Post entity.
type PostUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PostMutation
}

// SetUserID sets the "user_id" field.
func (_u *PostUpdateOne) SetUserID(v uuid.UUID) *PostUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableUserID(v *uuid.UUID) *PostUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetMarkdownContent sets the "markdown_content" field.
func (_u *PostUpdateOne) SetMarkdownContent(v string) *PostUpdateOne {
	_u.mutation.SetMarkdownContent(v)
	return _u
}

// SetNillableMarkdownContent sets the "markdown_content" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableMarkdownContent(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetMarkdownContent(*v)
	}
	return _u
}

// SetAtURL sets the "at_url" field.
func (_u *PostUpdateOne) SetAtURL(v string) *PostUpdateOne {
	_u.mutation.SetAtURL(v)
	return _u
}

// SetNillableAtURL sets the "at_url" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableAtURL(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetAtURL(*v)
	}
	return _u
}

// ClearAtURL clears the value of the "at_url" field.
func (_u *PostUpdateOne) ClearAtURL() *PostUpdateOne {
	_u.mutation.ClearAtURL()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PostUpdateOne) SetUpdatedAt(v time.Time) *PostUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PostMutation object of the builder.
func (_u *PostUpdateOne) Mutation() *PostMutation {
	return _u.mutation
}

// Where appends a list predicates to the PostUpdate builder.
func (_u *PostUpdateOne) Where(ps ...predicate.Post) *PostUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PostUpdateOne) Select(field string, fields ...string) *PostUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Post entity.
func (_u *PostUpdateOne) Save(ctx context.Context) (*Post, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostUpdateOne) SaveX(ctx context.Context) *Post {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PostUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PostUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := post.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *PostUpdateOne) sqlSave(ctx context.Context) (_node *Post, err error) {
	_spec := sqlgraph.NewUpdateSpec(post.Table, post.Columns, sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Post.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, post.FieldID)
		for _, f := range fields {
			if !post.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != post.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(post.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.MarkdownContent(); ok {
		_spec.SetField(post.FieldMarkdownContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.AtURL(); ok {
		_spec.SetField(post.FieldAtURL, field.TypeString, value)
	}
	if _u.mutation.AtURLCleared() {
		_spec.ClearField(post.FieldAtURL, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Post{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{post.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
