// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package client

import (
	"context"
	"github.com/ThreeDotsLabs/watermill/message"
	"sync"
)

// Ensure, that MessagePublisherMock does implement MessagePublisher.
// If this is not the case, regenerate this file with moq.
var _ MessagePublisher = &MessagePublisherMock{}

// MessagePublisherMock is a mock implementation of MessagePublisher.
//
//	func TestSomethingThatUsesMessagePublisher(t *testing.T) {
//
//		// make and configure a mocked MessagePublisher
//		mockedMessagePublisher := &MessagePublisherMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			PublishFunc: func(topic string, messages ...*message.Message) error {
//				panic("mock out the Publish method")
//			},
//		}
//
//		// use mockedMessagePublisher in code that requires MessagePublisher
//		// and then make assertions.
//
//	}
type MessagePublisherMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// PublishFunc mocks the Publish method.
	PublishFunc func(topic string, messages ...*message.Message) error

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// Publish holds details about calls to the Publish method.
		Publish []struct {
			// Topic is the topic argument value.
			Topic string
			// Messages is the messages argument value.
			Messages []*message.Message
		}
	}
	lockClose   sync.RWMutex
	lockPublish sync.RWMutex
}

// Close calls CloseFunc.
func (mock *MessagePublisherMock) Close() error {
	if mock.CloseFunc == nil {
		panic("MessagePublisherMock.CloseFunc: method is nil but MessagePublisher.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedMessagePublisher.CloseCalls())
func (mock *MessagePublisherMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// Publish calls PublishFunc.
func (mock *MessagePublisherMock) Publish(topic string, messages ...*message.Message) error {
	if mock.PublishFunc == nil {
		panic("MessagePublisherMock.PublishFunc: method is nil but MessagePublisher.Publish was just called")
	}
	callInfo := struct {
		Topic    string
		Messages []*message.Message
	}{
		Topic:    topic,
		Messages: messages,
	}
	mock.lockPublish.Lock()
	mock.calls.Publish = append(mock.calls.Publish, callInfo)
	mock.lockPublish.Unlock()
	return mock.PublishFunc(topic, messages...)
}

// PublishCalls gets all the calls that were made to Publish.
// Check the length with:
//
//	len(mockedMessagePublisher.PublishCalls())
func (mock *MessagePublisherMock) PublishCalls() []struct {
	Topic    string
	Messages []*message.Message
} {
	var calls []struct {
		Topic    string
		Messages []*message.Message
	}
	mock.lockPublish.RLock()
	calls = mock.calls.Publish
	mock.lockPublish.RUnlock()
	return calls
}

// Ensure, that MessageSubscriberMock does implement MessageSubscriber.
// If this is not the case, regenerate this file with moq.
var _ MessageSubscriber = &MessageSubscriberMock{}

// MessageSubscriberMock is a mock implementation of MessageSubscriber.
//
//	func TestSomethingThatUsesMessageSubscriber(t *testing.T) {
//
//		// make and configure a mocked MessageSubscriber
//		mockedMessageSubscriber := &MessageSubscriberMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			SubscribeFunc: func(ctx context.Context, topic string) (<-chan *message.Message, error) {
//				panic("mock out the Subscribe method")
//			},
//		}
//
//		// use mockedMessageSubscriber in code that requires MessageSubscriber
//		// and then make assertions.
//
//	}
type MessageSubscriberMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// SubscribeFunc mocks the Subscribe method.
	SubscribeFunc func(ctx context.Context, topic string) (<-chan *message.Message, error)

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// Subscribe holds details about calls to the Subscribe method.
		Subscribe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Topic is the topic argument value.
			Topic string
		}
	}
	lockClose     sync.RWMutex
	lockSubscribe sync.RWMutex
}

// Close calls CloseFunc.
func (mock *MessageSubscriberMock) Close() error {
	if mock.CloseFunc == nil {
		panic("MessageSubscriberMock.CloseFunc: method is nil but MessageSubscriber.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedMessageSubscriber.CloseCalls())
func (mock *MessageSubscriberMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// Subscribe calls SubscribeFunc.
func (mock *MessageSubscriberMock) Subscribe(ctx context.Context, topic string) (<-chan *message.Message, error) {
	if mock.SubscribeFunc == nil {
		panic("MessageSubscriberMock.SubscribeFunc: method is nil but MessageSubscriber.Subscribe was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Topic string
	}{
		Ctx:   ctx,
		Topic: topic,
	}
	mock.lockSubscribe.Lock()
	mock.calls.Subscribe = append(mock.calls.Subscribe, callInfo)
	mock.lockSubscribe.Unlock()
	return mock.SubscribeFunc(ctx, topic)
}

// SubscribeCalls gets all the calls that were made to Subscribe.
// Check the length with:
//
//	len(mockedMessageSubscriber.SubscribeCalls())
func (mock *MessageSubscriberMock) SubscribeCalls() []struct {
	Ctx   context.Context
	Topic string
} {
	var calls []struct {
		Ctx   context.Context
		Topic string
	}
	mock.lockSubscribe.RLock()
	calls = mock.calls.Subscribe
	mock.lockSubscribe.RUnlock()
	return calls
}
