// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"arktie.org/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// AccountDid applies equality check predicate on the "account_did" field. It's identical to AccountDidEQ.
func AccountDid(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAccountDid, v))
}

// EncryptionKey applies equality check predicate on the "encryption_key" field. It's identical to EncryptionKeyEQ.
func EncryptionKey(v []byte) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEncryptionKey, v))
}

// LastActiveAt applies equality check predicate on the "last_active_at" field. It's identical to LastActiveAtEQ.
func LastActiveAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLastActiveAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// AccountDidEQ applies the EQ predicate on the "account_did" field.
func AccountDidEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAccountDid, v))
}

// AccountDidNEQ applies the NEQ predicate on the "account_did" field.
func AccountDidNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAccountDid, v))
}

// AccountDidIn applies the In predicate on the "account_did" field.
func AccountDidIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldAccountDid, vs...))
}

// AccountDidNotIn applies the NotIn predicate on the "account_did" field.
func AccountDidNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAccountDid, vs...))
}

// AccountDidGT applies the GT predicate on the "account_did" field.
func AccountDidGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldAccountDid, v))
}

// AccountDidGTE applies the GTE predicate on the "account_did" field.
func AccountDidGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAccountDid, v))
}

// AccountDidLT applies the LT predicate on the "account_did" field.
func AccountDidLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldAccountDid, v))
}

// AccountDidLTE applies the LTE predicate on the "account_did" field.
func AccountDidLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAccountDid, v))
}

// AccountDidContains applies the Contains predicate on the "account_did" field.
func AccountDidContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldAccountDid, v))
}

// AccountDidHasPrefix applies the HasPrefix predicate on the "account_did" field.
func AccountDidHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldAccountDid, v))
}

// AccountDidHasSuffix applies the HasSuffix predicate on the "account_did" field.
func AccountDidHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldAccountDid, v))
}

// AccountDidEqualFold applies the EqualFold predicate on the "account_did" field.
func AccountDidEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldAccountDid, v))
}

// AccountDidContainsFold applies the ContainsFold predicate on the "account_did" field.
func AccountDidContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldAccountDid, v))
}

// EncryptionKeyEQ applies the EQ predicate on the "encryption_key" field.
func EncryptionKeyEQ(v []byte) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEncryptionKey, v))
}

// EncryptionKeyNEQ applies the NEQ predicate on the "encryption_key" field.
func EncryptionKeyNEQ(v []byte) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEncryptionKey, v))
}

// EncryptionKeyIn applies the In predicate on the "encryption_key" field.
func EncryptionKeyIn(vs ...[]byte) predicate.User {
	return predicate.User(sql.FieldIn(FieldEncryptionKey, vs...))
}

// EncryptionKeyNotIn applies the NotIn predicate on the "encryption_key" field.
func EncryptionKeyNotIn(vs ...[]byte) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldEncryptionKey, vs...))
}

// EncryptionKeyGT applies the GT predicate on the "encryption_key" field.
func EncryptionKeyGT(v []byte) predicate.User {
	return predicate.User(sql.FieldGT(FieldEncryptionKey, v))
}

// EncryptionKeyGTE applies the GTE predicate on the "encryption_key" field.
func EncryptionKeyGTE(v []byte) predicate.User {
	return predicate.User(sql.FieldGTE(FieldEncryptionKey, v))
}

// EncryptionKeyLT applies the LT predicate on the "encryption_key" field.
func EncryptionKeyLT(v []byte) predicate.User {
	return predicate.User(sql.FieldLT(FieldEncryptionKey, v))
}

// EncryptionKeyLTE applies the LTE predicate on the "encryption_key" field.
func EncryptionKeyLTE(v []byte) predicate.User {
	return predicate.User(sql.FieldLTE(FieldEncryptionKey, v))
}

// LastActiveAtEQ applies the EQ predicate on the "last_active_at" field.
func LastActiveAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLastActiveAt, v))
}

// LastActiveAtNEQ applies the NEQ predicate on the "last_active_at" field.
func LastActiveAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldLastActiveAt, v))
}

// LastActiveAtIn applies the In predicate on the "last_active_at" field.
func LastActiveAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldLastActiveAt, vs...))
}

// LastActiveAtNotIn applies the NotIn predicate on the "last_active_at" field.
func LastActiveAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldLastActiveAt, vs...))
}

// LastActiveAtGT applies the GT predicate on the "last_active_at" field.
func LastActiveAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldLastActiveAt, v))
}

// LastActiveAtGTE applies the GTE predicate on the "last_active_at" field.
func LastActiveAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldLastActiveAt, v))
}

// LastActiveAtLT applies the LT predicate on the "last_active_at" field.
func LastActiveAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldLastActiveAt, v))
}

// LastActiveAtLTE applies the LTE predicate on the "last_active_at" field.
func LastActiveAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldLastActiveAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasPosts applies the HasEdge predicate on the "posts" edge.
func HasPosts() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PostsTable, PostsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPostsWith applies the HasEdge predicate on the "posts" edge with a given conditions (other predicates).
func HasPostsWith(preds ...predicate.Post) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newPostsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
